CREATE TABLE [dbo].BPPurchase
(
	BPPurchaseID VARCHAR(10) NOT NULL CONSTRAINT DF_BPPurchase_BPBeliID DEFAULT(''),
	Tgl VARCHAR(10) NOT NULL CONSTRAINT DF_BPPurchase_Tgl DEFAULT('3000-01-01'), 
    Jam VARCHAR(8) NOT NULL CONSTRAINT DF_BPPurchase_Jam DEFAULT('00:00:00'),
	SupplierID VARCHAR(5) NOT NULL CONSTRAINT DF_BPPurchase_SupplierID DEFAULT(''),
	Keterangan VARCHAR(128) NOT NULL CONSTRAINT DF_BPPurchase_Keterangan DEFAULT(''),
	TotHargaPurchase DECIMAL(18,0) NOT NULL CONSTRAINT DF_BPPurchase_TotalHargaPurchase DEFAULT(0),
	TotHargaReceipt DECIMAL(18,0) NOT NULL CONSTRAINT DF_BPPurchase_TotalHargaReceipt DEFAULT(0),
	Diskon DECIMAL(18,0) NOT NULL CONSTRAINT DF_BPPurchase_Diskon DEFAULT(0),
	BiayaLain DECIMAL(18,0) NOT NULL CONSTRAINT DF_BPPurchase_BiayaLain DEFAULT(0),
	GrandTotal DECIMAL(18,0) NOT NULL CONSTRAINT DF_BPPurchase_GrandTotal DEFAULT(0),

	CONSTRAINT PK_BPBeli_BPBeliID PRIMARY KEY CLUSTERED(BPPurchaseID)
)
