CREATE TABLE [dbo].[ReceiptDetil]
(
	ReceiptID VARCHAR(10) NOT NULL CONSTRAINT DF_ReceiptDetil_ReceiptID DEFAULT(''),
	ReceiptDetilID VARCHAR(14) NOT NULL CONSTRAINT DF_ReceiptDetil_ReceiptDetilID DEFAULT(''),
	NoUrut DECIMAL(18,0) NOT NULL CONSTRAINT DF_ReceiptDetil_NoUrut DEFAULT(0),
	BrgID VARCHAR(5) NOT NULL CONSTRAINT DF_ReceiptDetil_BrgID DEFAULT(''),

	Qty DECIMAL(18,2) NOT NULL CONSTRAINT DF_ReceiptDetil_Qty DEFAULT(0),
	Harga DECIMAL(18,2) NOT NULL CONSTRAINT DF_ReceiptDetil_Harga DEFAULT(0),
	Diskon DECIMAL(18,2) NOT NULL CONSTRAINT DF_ReceiptDetil_Diskon DEFAULT(0),
	TaxProsen DECIMAL(18,2) NOT NULL CONSTRAINT DF_ReceiptDetil_TaxProsen DEFAULT(0),
	TaxRupiah DECIMAL(18,2) NOT NULL CONSTRAINT DF_ReceiptDetil_TaxRupiah DEFAULT(0),
	SubTotal DECIMAL(18,2) NOT NULL CONSTRAINT DF_ReceiptDetil_SubTotal DEFAULT(0),

	CONSTRAINT PK_ReceiptDetil_ReceiptDetilID PRIMARY KEY CLUSTERED(ReceiptDetilID)
)
