CREATE TABLE [dbo].[Receipt]
(
	ReceiptID VARCHAR(10) NOT NULL CONSTRAINT DF_Receipt_ReceiptID DEFAULT(''),
	Tgl VARCHAR(10) NOT NULL CONSTRAINT DF_Receipt_Tgl DEFAULT('3000-01-01'),
	Jam VARCHAR(8) NOT NULL CONSTRAINT DF_Receipt_Jam DEFAULT('00:00:00'),

	PurchaseID VARCHAR(10) NOT NULL CONSTRAINT DF_Receipt_PurchaseID DEFAULT(''),
	SupplierID VARCHAR(5) NOT NULL CONSTRAINT DF_Receipt_SupplierID DEFAULT(''),
	Keterangan VARCHAR(128) NOT NULL CONSTRAINT DF_Receipt_Keterangan DEFAULT(''),
	
	TotalHarga DECIMAL(18,0) NOT NULL CONSTRAINT DF_Receipt_TotalHarga DEFAULT(0),
	Diskon DECIMAL (18,0) NOT NULL CONSTRAINT DF_Receipt_Diskon DEFAULT(0),
	BiayaLain DECIMAL (18,0) NOT NULL CONSTRAINT DF_Receipt_BiayaLain DEFAULT(0),
	GrandTotal DECIMAL (18,0) NOT NULL CONSTRAINT DF_Receipt_GrandTotal DEFAULT(0),

	CONSTRAINT PK_Receipt_ReceiptID PRIMARY KEY CLUSTERED(ReceiptID)
)
