CREATE TABLE [dbo].[JenisBayar]
(
	JenisBayarID VARCHAR(3) NOT NULL CONSTRAINT DF_JenisBayar_JenisBayarID DEFAULT(''),
	JenisBayarName VARCHAR(20) NOT NULL CONSTRAINT DF_JenisBayar_JenisBayarName DEFAULT(''),
	KasTransferEdc VARCHAR(1) NOT NULL CONSTRAINT DF_JenisBayar_KasTransferEdc DEFAULT(0),
	NoUrut DECIMAL(18,0) NOT NULL CONSTRAINT DF_JenisBayar_NoUrut DEFAULT(0),

	CONSTRAINT PK_JenisBayar_JenisBayarID PRIMARY KEY CLUSTERED(JenisBayarID)
)
