CREATE TABLE [dbo].[OrderJual]
(
	OrderJualID VARCHAR(10) NOT NULL CONSTRAINT DF_OrderJual_OrderJualID DEFAULT(''),
	TglOrder VARCHAR(10) NOT NULL CONSTRAINT DF_OrderJual_TglOrder DEFAULT('3000-01-01'),
	JamOrder VARCHAR(8) NOT NULL CONSTRAINT DF_OrderJual_JamOrder DEFAULT('00:00:00'),
	UserrID VARCHAR(50) NOT NULL CONSTRAINT DF_OrderJual_UserrID DEFAULT(''),

	CustomerID VARCHAR(6) NOT NULL CONSTRAINT DF_OrderJual_CustomerID DEFAULT(''),
	BuyerName VARCHAR(30) NOT NULL CONSTRAINT DF_OrderJual_BuyerName DEFAULT(''),
	NoTelp VARCHAR(30) NOT NULL CONSTRAINT DF_OrderJual_NoTelp DEFAULT(''),
	Catatan VARCHAR(255) NOT NULL CONSTRAINT DF_OrderJual_Catatan DEFAULT(''),

	NilaiTotal DECIMAL(18,2) NOT NULL CONSTRAINT DF_OrderJual_NilaiTotal DEFAULT(0),
	NilaiDiskonLain DECIMAL(18,2) NOT NULL CONSTRAINT DF_OrderJual_NilaiDiskonLain DEFAULT(0),
	NilaiBiayaLain DECIMAL(18,2) NOT NULL CONSTRAINT DF_OrderJual_NilaiBiayaLain DEFAULT(0),
	NilaiGrandTotal DECIMAL(18,2) NOT NULL CONSTRAINT DF_OrderJual_NilaiGrandTotal DEFAULT(0),

	CONSTRAINT PK_OrderJual_OrderJualID PRIMARY KEY CLUSTERED (OrderJualID)
)
GO