CREATE TABLE [dbo].[Penjualan2]
(
	PenjualanID VARCHAR(10) NOT NULL CONSTRAINT DF_Penjualan2_PenjualanID DEFAULT(''),
	NoUrut DECIMAL(18,0) NOT NULL CONSTRAINT DF_Penjualan2_NoUrut DEFAULT(0),
	BrgID VARCHAR(5) NOT NULL CONSTRAINT DF_Penjualan2_BrgID DEFAULT(''),
	Qty DECIMAL(18,0) NOT NULL CONSTRAINT DF_Penjualan2_Qty DEFAULT(0),
	Harga DECIMAL(18,0) NOT NULL CONSTRAINT DF_Penjualan2_Harga DEFAULT(0),
	Diskon DECIMAL(18,0) NOT NULL CONSTRAINT DF_Penjualan2_Diskon DEFAULT(0),
	SubTotal DECIMAL(18,0) NOT NULL CONSTRAINT DF_Penjualan2_SubTotal DEFAULT(0)
)
GO

CREATE UNIQUE CLUSTERED INDEX IX_Penjualan2_PenjualanID_BrgID
	ON Penjualan2 (PenjualanID, BrgID)
GO


