CREATE TABLE [dbo].[PriceTagDetail]
(
	PriceTagID VARCHAR(3) NOT NULL CONSTRAINT DF_Pricing_PriceTagID DEFAULT (''), 
	QtyMin DECIMAL (18,0) NOT NULL CONSTRAINT DF_Pricing_Minimum DEFAULT(0),
	Price DECIMAL(18,0) NOT NULL CONSTRAINT DF_Pricing_Price DEFAULT(0),
	Discount DECIMAL(18,0) NOT NULL CONSTRAINT DF_Pricing_Discount DEFAULT(0),

    CONSTRAINT PK_Pricing_BrgIDMinumum PRIMARY KEY CLUSTERED (PriceTagID, QtyMin)
)
GO