CREATE TABLE [dbo].[PriceBrg]
(
	PriceID VARCHAR(4) NOT NULL CONSTRAINT DF_PriceBrg_PriceID DEFAULT(''),
	BrgID VARCHAR(5) NOT NULL CONSTRAINT DF_PriceBrg_BrgID DEFAULT(''),
)
GO

CREATE CLUSTERED INDEX IX_PriceBrg_PriceID 
	ON PriceBrg (PriceID)
GO

CREATE INDEX IX_PriceBrg_BrgID
	ON PriceBrg (BrgID)
	WITH(FILLFACTOR=90)
GO