CREATE TABLE [dbo].[PriceQty]
(
	PriceID VARCHAR(5) NOT NULL CONSTRAINT DF_PriceQty_PriceID DEFAULT(''),
	Qty DECIMAL(18,2) NOT NULL CONSTRAINT DF_PriceQty_Qty DEFAULT(0),
	Harga DECIMAL(18,2) NOT NULL CONSTRAINT DF_PriceQty_Harga DEFAULT(0),
	Diskon DECIMAL (18,2) NOT NULL CONSTRAINT DF_PriceQty_Diskon DEFAULT(0),
	
	CONSTRAINT PK_PriceQty_PriceID_Qty PRIMARY KEY (PriceID, Qty)
)
GO