CREATE TABLE [dbo].[ReturJual]
(
	ReturJualID VARCHAR(10) NOT NULL CONSTRAINT DF_ReturJual_ReturJualID DEFAULT(''),
	Tgl VARCHAR(10) NOT NULL CONSTRAINT DF_ReturJual_Tgl DEFAULT('3000-01-01'),
	Jam VARCHAR(8) NOT NULL CONSTRAINT DF_ReturJual_Jam DEFAULT('00:00:00'),
	PenjualanID VARCHAR(10) NOT NULL CONSTRAINT DF_ReturJual_PenjualanID DEFAULT(''),
	BuyerName VARCHAR(30) NOT NULL CONSTRAINT DF_ReturJual_BuyerName DEFAULT(''),
	Keterangan VARCHAR(128) NOT NULL CONSTRAINT DF_ReturJual_Keterangan DEFAULT(''),
	TotalRetur DECIMAL(18,0) NOT NULL CONSTRAINT DF_ReturJual_TotalRetur DEFAULT(0),

	CONSTRAINT ReturJualID PRIMARY KEY CLUSTERED(ReturJualID)
)
