CREATE TABLE [dbo].[ReturJualDetil]
(
	ReturJualID VARCHAR(10) NOT NULL CONSTRAINT DF_ReturJualDetil_ReturJualID DEFAULT(''),
	ReturJualDetilID VARCHAR(14) NOT NULL CONSTRAINT DF_ReturJualDetil_ReturJualDetilID DEFAULT(''),
	NoUrut DECIMAL(18,0) NOT NULL CONSTRAINT DF_ReturJualDetil_NoUrut DEFAULT(0),

	BrgID VARCHAR(5) NOT NULL CONSTRAINT DF_ReturJualDetil_BrgID DEFAULT(''),
	QtySisa DECIMAL(18,2) NOT NULL CONSTRAINT DF_ReturJualDetil_QtySisa DEFAULT(0),
	QtyRetur DECIMAL(18,2) NOT NULL CONSTRAINT DF_ReturJualDetil_QtyRetur DEFAULT(0),
	HargaRetur DECIMAL(18,2) NOT NULL CONSTRAINT DF_ReturJualDetil_HargaRetur DEFAULT(0),
	SubTotal DECIMAL(18,2) NOT NULL CONSTRAINT DF_ReturJualDetil_SubTotal DEFAULT(0),

	CONSTRAINT PK_ReturJualDetil_ReturJualDetilID PRIMARY KEY CLUSTERED(ReturJualDetilID)
)
