CREATE TABLE [dbo].[Biaya]
(
	BiayaID VARCHAR(10) NOT NULL CONSTRAINT DF_Biaya_BiayaID DEFAULT(''),
	Tgl  VARCHAR(10) NOT NULL CONSTRAINT DF_Biaya_Tgl  DEFAULT('3000-01-01'),
	Jam  VARCHAR(8) NOT NULL CONSTRAINT DF_Biaya_Jam DEFAULT('00:00:00'),
	Keterangan  VARCHAR(128) NOT NULL CONSTRAINT DF_Biaya_Keterangan DEFAULT(''),
	JenisBiayaID VARCHAR(3) NOT NULL CONSTRAINT DF_Biaya_JenisBiaya DEFAULT(''),
	JenisKasID VARCHAR(3) NOT NULL CONSTRAINT DF_Biaya_JenisKas DEFAULT(''),
	NilaiBiaya DECIMAL(18,0) NOT NULL CONSTRAINT DF_Biaya_NilaiBiaya DEFAULT(0),

	CONSTRAINT PK_Biaya_BiayaID PRIMARY KEY CLUSTERED(BiayaID)
)