CREATE TABLE [dbo].[BPHutangDetil]
(
	BPHutangID VARCHAR(10) NOT NULL CONSTRAINT DF_BPHutangDetil_BPHutangID DEFAULT(''),
	BPHutangDetilID VARCHAR(13) NOT NULL CONSTRAINT DF_BPHutangDetil_BPHutangDetilID DEFAULT(''),
	ReffID VARCHAR(10) NOT NULL CONSTRAINT DF_BPHutangDetil_ReffID DEFAULT(''),
	Tgl VARCHAR(10) NOT NULL CONSTRAINT DF_BPHutangDetil_Tgl DEFAULT(''),
	Jam VARCHAR(8) NOT NULL CONSTRAINT DF_BPHutangDetil_Jam DEFAULT(''),
	Keterangan VARCHAR(128) NOT NULL CONSTRAINT DF_BPHutangDetil_Keterangan DEFAULT(''),
	NilaiHutang DECIMAL(18,2) NOT NULL CONSTRAINT DF_BPHutangDetil_NilaiHutang DEFAULT(0),
	NilaiLunas DECIMAL(18,2) NOT NULL CONSTRAINT DF_BPHutangDetil_NilaiLunas DEFAULT(0),
 )