CREATE TABLE [dbo].[BPKasDetil]
(
	BPKasID VARCHAR(10) NOT NULL CONSTRAINT DF_BPKasDetil_BPKasID DEFAULT(''),
	BPKasDetilID VARCHAR(13) NOT NULL CONSTRAINT DF_BPKasDetil_BPKasDetilID DEFAULT(''),
	JenisKasID VARCHAR(3) NOT NULL CONSTRAINT DF_BPKasDetil_JenisKasID DEFAULT(''),
	NilaiKasMasuk DECIMAL(18,2) NOT NULL CONSTRAINT DF_BPKasDetil_NilaiKasMasuk DEFAULT(0),
	NilaiKasKeluar DECIMAL(18,2) NOT NULL CONSTRAINT DF_BPKasDetil_NilaiKasKeluar DEFAULT(0),

	CONSTRAINT PK_BPKasDetil_BPKasDetilID PRIMARY KEY CLUSTERED (BPKasDetilID)
)
