CREATE TABLE [dbo].[BPPiutangDetil]
(
	BPPiutangID VARCHAR(10) NOT NULL CONSTRAINT DF_BPPiutangDetil_BPPiutangID DEFAULT(''),
	BPPiutangDetilID VARCHAR(13) NOT NULL CONSTRAINT DF_BPPiutangDetil_BPPiutangDetilID DEFAULT(''),
	ReffID VARCHAR(10) NOT NULL CONSTRAINT DF_BPPiutangDetil_ReffID DEFAULT(''),
	Tgl VARCHAR(10) NOT NULL CONSTRAINT DF_BPPiutangDetil_Tgl DEFAULT('3000-01-01'),
	Jam VARCHAR(8) NOT NULL CONSTRAINT DF_BPPiutangDetil_Jam DEFAULT('00:00:00'),
	Keterangan VARCHAR(128) NOT NULL CONSTRAINT DF_BPPiutangDetil_Keterangan DEFAULT(''),
	NilaiPiutang DECIMAL(18,0) NOT NULL CONSTRAINT DF_BPPiutangDetil_NilaiPiutang DEFAULT(0),
	NilaiLunas DECIMAL(18,0) NOT NULL CONSTRAINT DF_BPPiutangDetil_NilaiLunas DEFAULT(0),

	CONSTRAINT PK_BPPiutangDetilID PRIMARY KEY CLUSTERED (BPPiutangDetilID)
)