CREATE TABLE [dbo].[Deposit]
(
	DepositID VARCHAR(10) NOT NULL CONSTRAINT DF_Deposit_DepositID DEFAULT(''),
	Tgl VARCHAR(10) NOT NULL CONSTRAINT DF_Deposit_Tgl DEFAULT('3000-01-01'),
	Jam VARCHAR(8) NOT NULL CONSTRAINT DF_Deposit_Jam DEFAULT('00:00:00'),
	PihakKeduaID VARCHAR(5) NOT NULL CONSTRAINT DF_Deposit_PihakKeduaID DEFAULT(''),
	Keterangan VARCHAR(128) NOT NULL CONSTRAINT DF_Deposit_Keterangan DEFAULT(''),
	JenisBayarID VARCHAR(5) NOT NULL CONSTRAINT DF_Deposit_JenisBayarID DEFAULT(''),
	NilaiDeposit DECIMAL(18,0) NOT NULL CONSTRAINT DF_Deposit_NilaiDeposit DEFAULT(0),

	CONSTRAINT DepositID PRIMARY KEY CLUSTERED(DepositID)
)
