CREATE TABLE [dbo].[LunasKasBon]
(
	LunasKasBonID VARCHAR(10) NOT NULL CONSTRAINT DF_LunasKasBon_LunasKasBonID DEFAULT(''),
	Tgl VARCHAR(10) NOT NULL CONSTRAINT DF_LunasKasBon_Tgl DEFAULT('3000-01-01'),
	Jam VARCHAR(10) NOT NULL CONSTRAINT DF_LunasKasBon_Jam DEFAULT('00:00:00'),
	PihakKeduaID VARCHAR(10) NOT NULL CONSTRAINT DF_LunasKasBon_PihakKeduaID DEFAULT(''),
	KasBonID VARCHAR(10) NOT NULL CONSTRAINT DF_LunasKasBon_KasBonID DEFAULT(''),
	NilaiSisaPiutang DECIMAL(18,0) NOT NULL CONSTRAINT DF_LunasKasBon_NilaiSisaPiutang DEFAULT(0),
	NilaiTotLunas DECIMAL(18,0) NOT NULL CONSTRAINT DF_LunasKasBon_NilaiTotLunas DEFAULT(0),

	CONSTRAINT PK_LunasKasBon_LunasKasBonID PRIMARY KEY CLUSTERED (LunasKasBonID)
)