CREATE TABLE [dbo].[Userr]
(
	[UserrID]		VARCHAR(10) NOT NULL CONSTRAINT DF_Userr_UserrID DEFAULT(''),
	[UserrName]		VARCHAR(30) NOT NULL CONSTRAINT DF_Userr_UserrName DEFAULT(''),
	[Password]		VARCHAR(128) NOT NULL CONSTRAINT DF_Userr_Password DEFAULT(''), 
	UserType VARCHAR(1) NOT NULL CONSTRAINT DF_Userr_UserrType DEFAULT('U'),
)
GO

CREATE UNIQUE CLUSTERED INDEX [IX_Userr_UserrID] ON [dbo].[Userr] (UserrID)
GO


