DELETE JenisBayar
GO

INSERT INTO JenisBayar 
VALUES ('KAS', 'Cash','K','K01',1)
GO

INSERT INTO JenisBayar
VALUES('TR1','Trf BCA','T','K02',4)
GO

INSERT INTO JenisBayar
VALUES('TR2','Trf BRI','T','K03',5)
GO

INSERT INTO JenisBayar
VALUES('ED1','EDC BCA','E','K02',2)
GO

INSERT INTO JenisBayar
VALUES ('ED2','EDC BRI','E', 'K03',5)
GO
