DELETE SubJenisBrg
INSERT INTO [dbo].[SubJenisBrg] ([SubJenisBrgID], [SubJenisBrgName], [JenisBrgID]) VALUES (N'ALS01', N'Mesin', N'ALS')
INSERT INTO [dbo].[SubJenisBrg] ([SubJenisBrgID], [SubJenisBrgName], [JenisBrgID]) VALUES (N'ALS02', N'Hot Gun', N'ALS')
INSERT INTO [dbo].[SubJenisBrg] ([SubJenisBrgID], [SubJenisBrgName], [JenisBrgID]) VALUES (N'ALS03', N'Lain-Lain', N'ALS')
INSERT INTO [dbo].[SubJenisBrg] ([SubJenisBrgID], [SubJenisBrgName], [JenisBrgID]) VALUES (N'ALS04', N'Rakel', N'ALS')
INSERT INTO [dbo].[SubJenisBrg] ([SubJenisBrgID], [SubJenisBrgName], [JenisBrgID]) VALUES (N'ALS05', N'Screen Sablon', N'ALS')
INSERT INTO [dbo].[SubJenisBrg] ([SubJenisBrgID], [SubJenisBrgName], [JenisBrgID]) VALUES (N'JAS01', N'Print Sublim', N'JAS')
INSERT INTO [dbo].[SubJenisBrg] ([SubJenisBrgID], [SubJenisBrgName], [JenisBrgID]) VALUES (N'KAO01', N'Kaos Polos', N'KAO')
INSERT INTO [dbo].[SubJenisBrg] ([SubJenisBrgID], [SubJenisBrgName], [JenisBrgID]) VALUES (N'KAO02', N'Kaos Premium', N'KAO')
INSERT INTO [dbo].[SubJenisBrg] ([SubJenisBrgID], [SubJenisBrgName], [JenisBrgID]) VALUES (N'KAO03', N'Kaos 3/4', N'KAO')
INSERT INTO [dbo].[SubJenisBrg] ([SubJenisBrgID], [SubJenisBrgName], [JenisBrgID]) VALUES (N'KAO04', N'Kaos Reject', N'KAO')
INSERT INTO [dbo].[SubJenisBrg] ([SubJenisBrgID], [SubJenisBrgName], [JenisBrgID]) VALUES (N'KAO05', N'Kaos Branded', N'KAO')
INSERT INTO [dbo].[SubJenisBrg] ([SubJenisBrgID], [SubJenisBrgName], [JenisBrgID]) VALUES (N'KAO06', N'Sweater', N'KAO')
INSERT INTO [dbo].[SubJenisBrg] ([SubJenisBrgID], [SubJenisBrgName], [JenisBrgID]) VALUES (N'KAO07', N'Smoke', N'KAO')
INSERT INTO [dbo].[SubJenisBrg] ([SubJenisBrgID], [SubJenisBrgName], [JenisBrgID]) VALUES (N'KAO08', N'Kaos Salur', N'KAO')
INSERT INTO [dbo].[SubJenisBrg] ([SubJenisBrgID], [SubJenisBrgName], [JenisBrgID]) VALUES (N'KAO09', N'Lain-Lain', N'KAO')
INSERT INTO [dbo].[SubJenisBrg] ([SubJenisBrgID], [SubJenisBrgName], [JenisBrgID]) VALUES (N'OBS01', N'Ink', N'OBS')
INSERT INTO [dbo].[SubJenisBrg] ([SubJenisBrgID], [SubJenisBrgName], [JenisBrgID]) VALUES (N'OBS02', N'SUPER WHITE', N'OBS')
INSERT INTO [dbo].[SubJenisBrg] ([SubJenisBrgID], [SubJenisBrgName], [JenisBrgID]) VALUES (N'OBS03', N'RUBBER BINDER', N'OBS')
INSERT INTO [dbo].[SubJenisBrg] ([SubJenisBrgID], [SubJenisBrgName], [JenisBrgID]) VALUES (N'OBS04', N'TRANS METAL BINDER', N'OBS')
INSERT INTO [dbo].[SubJenisBrg] ([SubJenisBrgID], [SubJenisBrgName], [JenisBrgID]) VALUES (N'OBS05', N'SPECIALIT BINDER', N'OBS')
INSERT INTO [dbo].[SubJenisBrg] ([SubJenisBrgID], [SubJenisBrgName], [JenisBrgID]) VALUES (N'OBS06', N'Fixed Agent', N'OBS')
INSERT INTO [dbo].[SubJenisBrg] ([SubJenisBrgID], [SubJenisBrgName], [JenisBrgID]) VALUES (N'OBS07', N'Obat Afdruk', N'OBS')
INSERT INTO [dbo].[SubJenisBrg] ([SubJenisBrgID], [SubJenisBrgName], [JenisBrgID]) VALUES (N'OBS08', N'Lain-Lain', N'OBS')
INSERT INTO [dbo].[SubJenisBrg] ([SubJenisBrgID], [SubJenisBrgName], [JenisBrgID]) VALUES (N'PAP01', N'Papper', N'PAP')
INSERT INTO [dbo].[SubJenisBrg] ([SubJenisBrgID], [SubJenisBrgName], [JenisBrgID]) VALUES (N'PIG01', N'Color', N'PIG')
INSERT INTO [dbo].[SubJenisBrg] ([SubJenisBrgID], [SubJenisBrgName], [JenisBrgID]) VALUES (N'PLF01', N'PVC', N'PLF')
INSERT INTO [dbo].[SubJenisBrg] ([SubJenisBrgID], [SubJenisBrgName], [JenisBrgID]) VALUES (N'PLF02', N'PU', N'PLF')
INSERT INTO [dbo].[SubJenisBrg] ([SubJenisBrgID], [SubJenisBrgName], [JenisBrgID]) VALUES (N'PLF03', N'FLOCK', N'PLF')
INSERT INTO [dbo].[SubJenisBrg] ([SubJenisBrgID], [SubJenisBrgName], [JenisBrgID]) VALUES (N'PLF04', N'FOIL', N'PLF')
INSERT INTO [dbo].[SubJenisBrg] ([SubJenisBrgID], [SubJenisBrgName], [JenisBrgID]) VALUES (N'PLF05', N'GLITTER', N'PLF')
INSERT INTO [dbo].[SubJenisBrg] ([SubJenisBrgID], [SubJenisBrgName], [JenisBrgID]) VALUES (N'PLF06', N'Glow In The Dark', N'PLF')
INSERT INTO [dbo].[SubJenisBrg] ([SubJenisBrgID], [SubJenisBrgName], [JenisBrgID]) VALUES (N'PLF07', N'Magic Puff', N'PLF')
INSERT INTO [dbo].[SubJenisBrg] ([SubJenisBrgID], [SubJenisBrgName], [JenisBrgID]) VALUES (N'PLF08', N'Polyfilm', N'PLF')
INSERT INTO [dbo].[SubJenisBrg] ([SubJenisBrgID], [SubJenisBrgName], [JenisBrgID]) VALUES (N'PLS01', N'Plastisol', N'PLS')
INSERT INTO [dbo].[SubJenisBrg] ([SubJenisBrgID], [SubJenisBrgName], [JenisBrgID]) VALUES (N'PLS02', N'Discharge', N'PLS')
