CREATE TABLE [dbo].[BPStok]
(
	BPStokID VARCHAR(15) NOT NULL CONSTRAINT DF_BPStok_BPStokID DEFAULT(''),
	ReffID VARCHAR(10) NOT NULL CONSTRAINT DF_BPStok_ReffID DEFAULT(''),

	StokControl VARCHAR(10) NOT NULL CONSTRAINT DF_BPStok_StokControl DEFAULT(''),
	Tgl VARCHAR(10) NOT NULL CONSTRAINT DF_BPStok_Tgl DEFAULT('3000-01-01'),
	Jam VARCHAR(8) NOT NULL CONSTRAINT DF_BPStok_Jam DEFAULT('00:00:00'),

	BrgID VARCHAR(5) NOT NULL CONSTRAINT DF_BPStok_BrgID DEFAULT(''),
	NilaiHpp DECIMAL(18,0) NOT NULL CONSTRAINT DF_BPStok_NilaiHpp DEFAULT(0),
	QtyIn DECIMAL(18,0) NOT NULL CONSTRAINT DF_BPStok_Qty DEFAULT(0),
	QtySisa DECIMAL(18,0) NOT NULL CONSTRAINT DF_BPStok_QtyOut DEFAULT(0),

	CONSTRAINT PK_BPStok_BPStokID PRIMARY KEY(BPStokID)
)
