CREATE TABLE [dbo].[Brg]
(
	BrgID VARCHAR(5) NOT NULL CONSTRAINT DF_Brg_BrgID DEFAULT(''),
	BrgName VARCHAR(40) NOT NULL CONSTRAINT DF_Brg_BrgName DEFAULT(''),
	BrgNamePrint VARCHAR(27) NOT NULL CONSTRAINT DF_Brg_BrgNamePrint DEFAULT(''),
	Keterangan VARCHAR(512) NOT NULL CONSTRAINT DF_Brg_Keterangan DEFAULT(''), 
    SubJenisBrgID VARCHAR(5) NOT NULL CONSTRAINT DF_Brg_SubJenisBrgID DEFAULT(''),
	MerkID VARCHAR(5) NOT NULL CONSTRAINT DF_Brg_MerkID DEFAULT(''),
	MerkName VARCHAR(30) NOT NULL CONSTRAINT DF_Brg_MerkName DEFAULT(''),
	ColorID VARCHAR(20) NOT NULL CONSTRAINT DF_Brg_ColorID DEFAULT(''),
	ColorName VARCHAR(30) NOT NULl CONSTRAINT DF_Brg_ColorName DEFAULT(''),
	Kemasan VARCHAR(20) NOT NULL CONSTRAINT DF_Brg_Kemasan DEFAULT(''),
	
	CreateTimestamp DATETIME NOT NULL CONSTRAINT DF_Brg_CreateTimestamp DEFAULT(getdate()),
	UpdateTimestamp DATETIME NOT NULL CONSTRAINT DF_Brg_UpdateTimestamp DEFAULT(getdate()),

	IsAktif BIT NOT NULL CONSTRAINT DF_Brg_IsAktif DEFAULT(1), 
    CONSTRAINT PK_Brg_BrgID PRIMARY KEY CLUSTERED (BrgID)
)

GO

CREATE INDEX IX_Brg_SubJenisBrgID_MerkID_ColorID
	ON Brg  (SubJenisBrgID, MerkID, ColorID)
		WITH(FILLFACTOR=80)
GO