CREATE TABLE [dbo].[Brg]
(
	BrgID VARCHAR(5) NOT NULL CONSTRAINT DF_Brg_BrgID DEFAULT(''),
	BrgName VARCHAR(30) NOT NULL CONSTRAINT DF_Brg_BrgName DEFAULT(''),
	TipeBrgID VARCHAR(5) NOT NULL CONSTRAINT DF_Brg_TipeBrgID DEFAULT(''),
	Keterangan VARCHAR(512) NOT NULL CONSTRAINT DF_Brg_Keterangan DEFAULT('')
)
