CREATE TABLE [dbo].[Color]
(
	[ColorID] VARCHAR(10) NOT NULL CONSTRAINT DF_Color_ColorID DEFAULT(' '),
	ColorName VARCHAR(30) NOT NULL CONSTRAINT DF_Color_ColorName DEFAULT(' '),
	RedValue DECIMAL(18,0) NOT NULL CONSTRAINT DF_Color_RedValue DEFAULT(0),
	GreenValue DECIMAL (18,0) NOT NULL CONSTRAINT DF_Color_GreenValue DEFAULT(0),
	BlueValue DECIMAL(18,0) NOT NULL CONSTRAINT DF_Color_BlueValue DEFAULT(0)
)
GO

CREATE UNIQUE CLUSTERED INDEX IX_Color_ColorID
	ON Color(ColorID)
GO