CREATE TABLE [dbo].[JenisBrg2Tipe]
(
	JenisBrgID VARCHAR(3) NOT NULL CONSTRAINT DF_JenisBrgTipe_JenisBrgID DEFAULT(''),
	TipeBrgID VARCHAR(5) NOT NULL CONSTRAINT DF_JenisBrgTipe_TipeBrgID DEFAULT(''),
	NoUrut DECIMAL(18,0) NOT NULL CONSTRAINT DF_JenisBrgTipe_NoUrut DEFAULT(0)
)
GO

CREATE UNIQUE CLUSTERED INDEX IX_JenisBrgTipe_JenisBrgTipeID
	ON JenisBrg2Tipe (JenisBrgID, TipeBrgID)
GO

