CREATE TABLE [dbo].[Merk]
(
	[MerkID] VARCHAR(3) NOT NULL CONSTRAINT DF_Merk_MerkID DEFAULT(''),
	MerkName VARCHAR(30) NOT NULL CONSTRAINT DF_Merk_MerkName DEFAULT(''),
)
GO

CREATE UNIQUE CLUSTERED INDEX IX_Merk_MerkID
	ON Merk(MerkID)
GO