CREATE TABLE [dbo].[ProduksiHasil]
(
	ProduksiID VARCHAR(10) NOT NULL CONSTRAINT DF_ProduksiHasil_ProduksiID DEFAULT(''),
	ProduksiID2 VARCHAR(14) NOT NULL CONSTRAINT DF_ProduksiHasil_ProduksiID2 DEFAULT(''),
	NoUrut DECIMAL(18,0) NOT NULL CONSTRAINT DF_ProduksiHasil_NoUrut DEFAULT(0),
	BrgID VARCHAR(5) NOT NULL CONSTRAINT DF_ProduksiHasil_BrgID DEFAULT(''),
	Qty DECIMAL(18,0) NOT NULL CONSTRAINT DF_ProduksiHasil_Qty DEFAULT(0),
	Hpp DECIMAL(18,0) NOT NULL CONSTRAINT DF_ProduksiHasil_Hpp DEFAULT(0),
	StokControl VARCHAR(20) NOT NULL CONSTRAINT DF_ProduksiHasil_StokControl DEFAULT(''),

	CONSTRAINT PK_ProduksiHasil_ProduksiID2 PRIMARY KEY CLUSTERED(ProduksiID2)
)
