CREATE TABLE [dbo].[Repack]
(
	RepackID VARCHAR(10) NOT NULL CONSTRAINT DF_Repack_RepackID DEFAULT(''),
	Tgl VARCHAR(10) NOT NULL CONSTRAINT DF_Repack_Tgl DEFAULT('3000-01-01'),
	Jam VARCHAR(8) NOT NULL CONSTRAINT DF_Repack_Jam DEFAULT('00:00:00'),

	BPStokID VARCHAR(15) NOT NULL CONSTRAINT DF_Repack_BPStokID DEFAULT(''),
	BrgIDMaterial VARCHAR(5) NOT NULL CONSTRAINT DF_Repack_BrgIDMaterial DEFAULT(''),
	QtyMaterial DECIMAL(18,0) NOT NULL CONSTRAINT DF_Repack_QtyMaterial DEFAULT(0),
	HppMaterial DECIMAL(18,0) NOT NULL CONSTRAINT DF_Repack_HppMaterial DEFAULT(0),
	
	BrgIDHasil VARCHAR(5) NOT NULL CONSTRAINT DF_Repack_BrgIDHasil DEFAULT(''),
	SlotControl VARCHAR(10) NOT NULL CONSTRAINT DF_Repack_SlotControl DEFAULT(''),
	QtyHasil DECIMAL(18,0) NOT NULL CONSTRAINT DF_Repack_QtyHasil DEFAULT(0),
	HppHasil DECIMAL(18,0) NOT NULL CONSTRAINT DF_Repack_HppHasil DEFAULT(0),

	CONSTRAINT PK_Repack_RepackID PRIMARY KEY CLUSTERED (RepackID)
)
