CREATE TABLE [dbo].[SaldoStok]
(
	SaldoStokID VARCHAR(10) NOT NULL CONSTRAINT DF_SaldoStok_SaldoStokID DEFAULT(''),
	BrgID VARCHAR(5) NOT NULL CONSTRAINT DF_SaldoStok_BrgID DEFAULT(''),
	QtyIn DECIMAL(18,0) NOT NULL CONSTRAINT DF_SaldoStok_QtyIn DEFAULT(0),
	QtyNow DECIMAL(18,0) NOT NULL CONSTRAINT DF_SaldoStok_QtyNow DEFAULT(0),
	Hpp DECIMAL(18,0) NOT NULL CONSTRAINT DF_SaldoStok_Hpp DEFAULT(0), 
    MutasiID VARCHAR(10) NOT NULL CONSTRAINT DF_SaldoStok_MutasiID DEFAULT(''), 
    TglMutasi VARCHAR(10) NOT NULL CONSTRAINT DF_SaldoStok_TglMutasi DEFAULT ('3000-01-01'),
	JamMutasi VARCHAR(8) NOT NULL CONSTRAINT DF_SaldoStok_JamMutasi DEFAULT('00:00:00'),

	CONSTRAINT SaldoStokID PRIMARY KEY CLUSTERED (SaldoStokID),
)
GO

CREATE INDEX IX_SaldoStok_BrgIDTglJam
	ON SaldoStok (BrgID, TglMutasi, JamMutasi)
	INCLUDE (QtyNow, Hpp)
	WITH (FILLFACTOR=80)
GO