CREATE TABLE [dbo].[StokInOut]
(
	StokInID VARCHAR(12) NOT NULL CONSTRAINT DF_StokInOut_StokInID DEFAULT(''),
	StokInOutID VARCHAR(16) NOT NULL CONSTRAINT DF_StokInOut_StokInOutID DEFAULT(''),

	TglTrs VARCHAR(10) NOT NULL CONSTRAINT DF_StokInOut_TglTrs DEFAULT('3000-01-01'),
	JamTrs VARCHAR(8) NOT NULL CONSTRAINT DF_StokInOut_JamTrs DEFAULT('00:00:00'),
	ReffTrsID VARCHAR(10) NOT NULL CONSTRAINT DF_StokInOut_ReffTrsID DEFAULT(''),
	JenisMutasiID VARCHAR(5) NOT NULL CONSTRAINT DF_StokInOut_JenisMutasiID DEFAULT(''),

	BrgID VARCHAR(5) NOT NULL CONSTRAINT DF_StokInOut_BrgID DEFAULT(''),
	StokControlID VARCHAR(15) NOT NULL CONSTRAINT DF_StokInOut_StokControlID DEFAULT(''),

	QtyIn DECIMAL(18,2) NOT NULL CONSTRAINT DF_StokInOut_QtyIn DEFAULT(0),
	QtyOut DECIMAL(18,2) NOT NULL CONSTRAINT DF_StokInOut_QtyOut DEFAULT(0),
	Hpp DECIMAL(18,2) NOT NULL CONSTRAINT DF_StokInOut_Hpp DEFAULT(0),
	HargaJual DECIMAL (18,2) NOT NULL CONSTRAINT DF_StokInOut_HargaJual DEFAULT(0),

	CONSTRAINT PK_StokInOut_StokInOutID PRIMARY KEY CLUSTERED (StokInOutID)
)
GO

CREATE INDEX IX_StokInOut_BrgID_StokControlID
	ON StokInOut (BrgID, StokControlID)
GO

CREATE INDEX IX_StokInOut_TglTrs_JamTrs_BrgID
	ON StokInOut (TglTrs, JamTrs, BrgID)
GO