CREATE TABLE [dbo].[StokAdjustment]
(
	StokAdjustmentID VARCHAR(10) NOT NULL CONSTRAINT DF_StokAdjustment_StokAdjustmentID DEFAULT(''),
	TglTrs VARCHAR(10) NOT NULL CONSTRAINT DF_StokAdjustment_TglTrs DEFAULT('3000-01-01'),
	JamTrs VARCHAR(8) NOT NULL CONSTRAINT DF_StokAdjustment_JamTrs DEFAULT('00:00:00'),
	UserrID VARCHAR(30) NOT NULL CONSTRAINT DF_StokAdjustment_UserrID DEFAULT(''),
	TglVoid VARCHAR(10) NOT NULL CONSTRAINT DF_StokAdjustment_TglVoid DEFAULT('3000-01-01'),
	JamVoid VARCHAR(8) NOT NULL CONSTRAINT DF_StokAdjustment_JamVoid DEFAULT('00:00:00'),
	UserrIDVoid VARCHAR(30) NOT NULL CONSTRAINT DF_StokAdjustment_UserrIDVoid DEFAULT(''),
	Keterangan VARCHAR(255) NOT NULL CONSTRAINT DF_STokAdjustment_Keterangan DEFAULT(''),

	CONSTRAINT PK_StokAdjustment_StokAdjustmentID PRIMARY KEY CLUSTERED(StokAdjustmentID)
)
