CREATE TABLE [dbo].[StokControl2]
(
	StokControl2ID VARCHAR(16) NOT NULL CONSTRAINT DF_StokDetil_StokDetilID DEFAULT(''),
	StokControlID VARCHAR(13) NOT NULL CONSTRAINT DF_StokDetil_StokID DEFAULT(''),
	TglTrs VARCHAR(10) NOT NULL CONSTRAINT DF_StokDetil_TglTrs DEFAULT('3000-01-01'),
	JamTrs VARCHAR(8) NOT NULL CONSTRAINT DF_StokDetil_JamTrs DEFAULT('00:00:00'),
	ReffTrsID VARCHAR(10) NOT NULL CONSTRAINT DF_StokDetil_ReffTrsID DEFAULT(''),
	JenisMutasiID VARCHAR(5) NOT NULL CONSTRAINT DF_StokDetil_JenisMutasiID DEFAULT(''),
	QtyIn DECIMAL(18,0) NOT NULL CONSTRAINT DF_StokDetil_QtyIn DEFAULT(0),
	QtyOut DECIMAL(18,0) NOT NULL CONSTRAINT DF_StokDetil_QtyOut DEFAULT(0),
	NilaiIn DECIMAL (18,0) NOT NULL CONSTRAINT DF_StokDetil_NilaiIn DEFAULT(0),
	NilaiOut DECIMAL (18,0) NOT NULL CONSTRAINT DF_StokDetil_NilaiOut DEFAULT(0)
)
GO

CREATE UNIQUE INDEX IX_StokDetil_StokDetilID
	ON StokControl2 (StokControl2ID)
	WITH(FILLFACTOR=70)
GO

CREATE CLUSTERED INDEX IX_StokDetil_StokID_TglTrs_JamTrs
	ON StokControl2 (StokControlID, TglTrs, JamTrs)
GO