CREATE TABLE [dbo].[StokIn]
(
	StokInID VARCHAR(12) NOT NULL CONSTRAINT DF_StokIn_StokID DEFAULT(''),
	BrgID VARCHAR(5) NOT NULL CONSTRAINT DF_StokIn_BrgID DEFAULT(''),
	TglMasuk VARCHAR(10) NOT NULL CONSTRAINT DF_StokIn_TglMasuk DEFAULT('3000-01-01'),
	JamMasuk VARCHAR(8) NOT NULL CONSTRAINT DF_StokIn_JamMasuk DEFAULT('00:00:00'),

	--Transaksi yang menerbitkan stok ini
	TrsMasukID VARCHAR(10) NOT NULL CONSTRAINT DF_StokIn_TrsMasukID DEFAULT(''),

	QtyIn DECIMAL(18,0) NOT NULL CONSTRAINT DF_StokIn_QtyIn DEFAULT(0),
	QtySaldo DECIMAL(18,0) NOT NULL CONSTRAINT DF_StokIn_QtySaldo DEFAULT(0),
	Hpp DECIMAL NOT NULL CONSTRAINT DF_StokIn_Hpp DEFAULT (0), 

	StokControlID VARCHAR(13) NOT NULL CONSTRAINT DF_StokIn_StokControlID DEFAULT(''),
	TrsDOID VARCHAR(10) NOT NULL CONSTRAINT DF_StokIn_TrsDOID DEFAULT(''),

    CONSTRAINT PK_StokIn_StokInID PRIMARY KEY CLUSTERED (StokInID)
)
GO

CREATE INDEX IX_StokIn_StokControlID 
	ON StokIn (StokControlID)
GO

CREATE INDEX IX_Stok_BrgID_TglMasuk_JamMasuk
	ON StokIn (BrgID, TglMasuk, JamMasuk)
GO
